apiVersion: v1
kind: Secret
metadata:
  name: argo.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-service-account-token
data:
  # TODO: Run `kubectl get secret argo.service-account-token -o=jsonpath='{.data.token}' | base64 --decode`
  ARGO_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFMZjBoWmJLYzNlT2VFb2FSblNLcDZUbFE1NFFUVHg3VWRteUZMZi1LZVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ28uc2VydmljZS1hY2NvdW50LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFyZ28iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJjYmJmMzdiYi1kYTNlLTQ3ZDQtYjFmYy1jMTM1MWU2NjRjODAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDphcmdvIn0.0EaEfwbzWP8gRSZfxdATe10gwLmRnwfzbRmYLAJziioYDk3pWHH76Xj6TpTg1JorLmlN98l_t6KlsJLx4e89Fncj4LPAR3qjHxI-6HzvMQDRjcL9cKXCq45w4Q5LEuQPppCCse-RWNbZ7iuvOf7Pt_Os6NRIwhx5ZAo8dp66WkInEFudEh3IeB0ornwnhCryD-Z0SnPyrjkrP4InvHlNmQef_SGhM3DMtWStgGFlP0HYdRUfhEvr9rC5QtOZt_pY_5lkTnT5tDbMVHNM8L8ASPD8J6aPIwUApzfpREZXkjFCl7mQv13KKvfRBqDKn97iB8d60oKKgPkYX7gGsvSDbw%
