kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo
resources:
  - namespace/argo.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.0/install.yaml
  - secret/argo-postgres-secret.yaml
  - pdb/workflow-controller.yaml
  - pdb/argo-server.yaml
patches:
  - path: configmap/workflow-controller-configmap-patch.yaml
  - path: deployment/workflow-controller-patch.yaml
  - path: deployment/argo-server-patch.yaml
