kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo-events
resources:
  - namespace/argo-events.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/namespace-install.yaml
