apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  workflowDefaults: |
    metadata:
      annotations:
        workflows.argoproj.io/notification: true
        workflows.argoproj.io/snitch-token: none
      labels:
        workflows.argoproj.io/creator: nobody
        workflows.argoproj.io/owner: nobody
        workflows.argoproj.io/name: none
    spec:
      # ttlStrategy:
      #   secondsAfterCompletion: 10
      #   secondsAfterSuccess: 10
      #   secondsAfterFailure: 10
      # podGC:
      #   strategy: OnPodCompletion
      serviceAccountName: argo
      onExit: exit-handler
      metrics:
        prometheus:
          - name: exec_duration_gauge
            help: "Duration of execution by name"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: workflow_name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_origin_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            gauge:
              value: "{{ workflow.duration }}"
          - name: exec_status_count
            help: "Count of execution by status"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: workflow_name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_origin_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            counter:
              value: 1
      templateDefaults:
        metrics:
          prometheus:
            - name: template_duration_gauge
              help: "Duration of execution by name"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: workflow_name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_origin_name
                  value: "{{ workflow.name }}"
              gauge:
                value: "{{ workflow.duration }}"
            - name: template_status_count
              help: "Count of step execution by result status"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: workflow_name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_origin_name
                  value: "{{ workflow.name }}"
                - key: status
                  value: "{{ status }}"
              counter:
                value: 1
      templates:
        - name: exit-handler
          steps:
          - - name: datadog-metrics
              template: metrics
            - name: deadmans-snitch
              when: "'{{ workflow.annotations.workflows.argoproj.io/snitch-token }}' != none"
              inline:
                container:
                  image: public.ecr.aws/amazonlinux/amazonlinux:latest
                  command: [curl]
                  args: ["https://nosnch.in/{{ workflow.annotations.workflows.argoproj.io/snitch-token }}"]
            - name: slack-notification
              when: "{{ workflow.annotations.workflows.argoproj.io/notification }} == true"
              template: notification
        - name: metrics
          steps:
          - - name: exit-status-count
              template: datadog
              arguments:
                parameters:
                  - name: name
                    value: "argo.argo_workflows_exit_status_count"
                  - name: type
                    value: 1
                  - name: value
                    value: 1
            - name: exit-duration-gauge
              template: datadog
              arguments:
                parameters:
                  - name: name
                    value: "argo.argo_workflows_exit_duration_gauge"
                  - name: type
                    value: 3
                  - name: value
                    value: "{{ workflow.duration }}"
        - name: datadog
          inputs:
            parameters:
              - name: name
              - name: type
              - name: value
          container:
            image: public.ecr.aws/amazonlinux/amazonlinux:latest
            command: [bash, -c]
            args:
              - >-
                curl -X POST https://api.datadoghq.com/api/v2/series
                -H "Accept: application/json"
                -H "Content-Type: application/json"
                -H "DD-API-KEY: ${DD_API_KEY}"
                -d "{\"series\": [{\"metric\": \"{{ inputs.parameters.name }}\",\"type\": {{ inputs.parameters.type }},\"points\": [{\"timestamp\": $(date +%s),\"value\": "{{ inputs.parameters.value }}"}],\"tags\": [\"owner:{{ workflow.labels.workflows.argoproj.io/owner }}\",\"workflow_name:{{ workflow.labels.workflows.argoproj.io/name }}\",\"workflow_origin_name:{{ workflow.name }}\",\"status:{{ workflow.status }}\"]}]}"
            envFrom:
              - secretRef:
                  name: dd-credentials
        - name: notification
          steps:
          - - name: cry
              when: "{{workflow.status}} != Succeeded"
              template: slack
              arguments:
                parameters:
                  - name: color
                    value: danger
                  - name: message
                    value: |
                      @{{ workflow.labels.workflows.argoproj.io/owner }}
                      :exclamation: `{{ workflow.name }}` is `{{ workflow.status }}` :exclamation:
                      ```
                      {{ workflow.failures }}
                      ```
        - name: slack
          inputs:
            parameters:
              - name: color
              - name: message
              - name: header
                default: "Argo Workflows Notification"
          container:
            image: ghcr.io/nagomiso/slackutils:v0.2.1
            envFrom:
            - secretRef:
                name: slack-config
            args:
              - webhook-send
              - --color
              - "{{ inputs.parameters.color }}"
              - --header
              - "{{ inputs.parameters.header }}"
              - --message
              - "{{ inputs.parameters.message }}"
              # https://argoproj.github.io/argo-workflows/variables/#global
              - --field
              - |
                *workflow:*
                <https://localhost:2746/workflows/{{ workflow.namespace }}/{{ workflow.name }}?tab=workflow&uid={{ workflow.uid }}|{{ workflow.name }}>
              - --field
              - |
                *owner:*
                {{ workflow.labels.workflows.argoproj.io/owner }}
              - --field
              - |
                *creator:*
                {{ workflow.labels.workflows.argoproj.io/creator }}
              - --field
              - |
                *creationTimestamp:*
                {{ workflow.creationTimestamp }}
              - --field
              - |
                *duration:*
                {{ workflow.duration }}s
