apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  workflowDefaults: |
    metadata:
      annotations:
        workflows.argoproj.io/notification: true
        workflows.argoproj.io/snitch: none
      labels:
        workflows.argoproj.io/creator: nobody
        workflows.argoproj.io/owner: nobody
        workflows.argoproj.io/name: none
    spec:
      ttlStrategy:
        secondsAfterCompletion: 10
        secondsAfterSuccess: 10
        secondsAfterFailure: 10
      podGC:
        strategy: OnPodCompletion
      serviceAccountName: argo
      onExit: exit-handler
      metrics:
        prometheus:
          - name: exec_duration_gauge
            help: "Duration of execution by name"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: workflow_name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_origin_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            gauge:
              value: "{{ workflow.duration }}"
          - name: exec_status_count
            help: "Count of execution by status"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: workflow_name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_origin_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            counter:
              value: 1
      templateDefaults:
        metrics:
          prometheus:
            - name: template_duration_gauge
              help: "Duration of execution by name"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: workflow_name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_origin_name
                  value: "{{ workflow.name }}"
              gauge:
                value: "{{ workflow.duration }}"
            - name: template_status_count
              help: "Count of step execution by result status"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: workflow_name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_origin_name
                  value: "{{ workflow.name }}"
                - key: status
                  value: "{{ status }}"
              counter:
                value: 1
      templates:
        - name: exit-handler
          steps:
          - - name: deadmans-snitch
              when: "'{{ workflow.annotations.workflows.argoproj.io/snitch }}' != none"
              template: curl
              arguments:
                parameters:
                  - name: url
                    value: "{{ workflow.annotations.workflows.argoproj.io/snitch }}"
            - name: celebrate
              when: "{{ workflow.status }} == Succeeded"
              template: slack
              arguments:
                parameters:
                  - name: color
                    value: good
                  - name: message
                    value: |
                      `{{ workflow.name }}` is `{{ workflow.status }}`
            - name: cry
              when: "{{workflow.status}} != Succeeded"
              template: slack
              arguments:
                parameters:
                  - name: color
                    value: danger
                  - name: message
                    value: |
                      @{{ workflow.labels.workflows.argoproj.io/owner }}
                      :exclamation: `{{ workflow.name }}` is `{{ workflow.status }}` :exclamation:
                      ```
                      {{ workflow.failures }}
                      ```
        - name: curl
          inputs:
            parameters:
              - name: url
          container:
            image: public.ecr.aws/amazonlinux/amazonlinux:latest
            command: [curl]
            args: ["{{ inputs.parameters.url }}"]
        - name: slack
          inputs:
            parameters:
              - name: color
              - name: message
              - name: header
                default: "Argo Workflows Notification"
          steps:
          - - name: message
              when: "{{ workflow.annotations.workflows.argoproj.io/notification }} == true"
              inline:
                container:
                  image: ghcr.io/nagomiso/slackutils:v0.2.1
                  envFrom:
                  - secretRef:
                      name: slack-config
                  args:
                    - webhook-send
                    - --color
                    - "{{ inputs.parameters.color }}"
                    - --header
                    - "{{ inputs.parameters.header }}"
                    - --message
                    - "{{ inputs.parameters.message }}"
                    # https://argoproj.github.io/argo-workflows/variables/#global
                    - --field
                    - |
                      *workflow:*
                      <https://localhost:2746/workflows/{{ workflow.namespace }}/{{ workflow.name }}?tab=workflow&uid={{ workflow.uid }}|{{ workflow.name }}>
                    - --field
                    - |
                      *owner:*
                      {{ workflow.labels.workflows.argoproj.io/owner }}
                    - --field
                    - |
                      *creator:*
                      {{ workflow.labels.workflows.argoproj.io/creator }}
                    - --field
                    - |
                      *creationTimestamp:*
                      {{ workflow.creationTimestamp }}
                    - --field
                    - |
                      *duration:*
                      {{ workflow.duration }}s
