apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  workflowDefaults: |
    metadata:
      annotations:
        karpenter.sh/do-not-evict: true
      labels:
        workflows.argoproj.io/owner: nobody
        workflows.argoproj.io/name: none
    spec:
      serviceAccountName: argo
      metrics:
        prometheus:
          - name: exec_duration_gauge
            help: "Duration of execution by name"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            gauge:
              value: "{{ workflow.duration }}"
          - name: exec_status_count
            help: "Count of execution by status"
            labels:
              - key: owner
                value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
              - key: name
                value: "{{ workflow.labels.workflows.argoproj.io/name }}"
              - key: workflow_name
                value: "{{ workflow.name }}"
              - key: status
                value: "{{ workflow.status }}"
            counter:
              value: 1

      templateDefaults:
        metrics:
          prometheus:
            - name: template_duration_gauge
              help: "Duration of execution by name"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_name
                  value: "{{ workflow.name }}"
              gauge:
                value: "{{ workflow.duration }}"
            - name: template_status_count
              help: "Count of step execution by result status"
              labels:
                - key: owner
                  value: "{{ workflow.labels.workflows.argoproj.io/owner }}"
                - key: name
                  value: "{{ workflow.labels.workflows.argoproj.io/name }}"
                - key: workflow_name
                  value: "{{ workflow.name }}"
                - key: status
                  value: "{{ status }}"
              counter:
                value: 1

      hooks:
        # on-start:
        #   expression: workflow.status == "Running"
        #   template: notify-slack
        #   arguments:
        #     parameters:
        #       - name: color
        #         value: good
        on-succeed:
          expression: workflow.status == "Succeeded"
          template: notify-slack
          arguments:
            parameters:
              - name: color
                value: good
        on-fail:
          expression: workflow.status == "Failed" || workflow.status == "Error"
          template: notify-slack
          arguments:
            parameters:
              - name: message
                value: |
                  @{{ workflow.labels.workflows.argoproj.io/owner }}
                  :exclamation: `{{ workflow.name }}` is `{{ workflow.status }}` :exclamation:
                  ```
                  {{ workflow.failures }}
                  ```
              - name: color
                value: danger

      templates:
        - name: notify-slack
          inputs:
            parameters:
              - name: message
                default: "`{{ workflow.name }}` is `{{ workflow.status }}`"
              - name: color
                default: good
          steps:
            - - name: slack-bot
                template: message
                arguments:
                  parameters:
                    - name: message
                      value: "{{ inputs.parameters.message }}"
                    - name: color
                      value: "{{ inputs.parameters.color }}"
        - name: message
          inputs:
            parameters:
              - name: color
              - name: message
              - name: header
                default: "Argo Workflows"
          container:
            image: ghcr.io/nagomiso/slackutils:v0.2.1
            envFrom:
            - secretRef:
                name: slack-config
            args:
              - webhook-send
              - --color
              - "{{ inputs.parameters.color }}"
              - --header
              - "{{ inputs.parameters.header }}"
              - --message
              - "{{ inputs.parameters.message }}"
              # https://argoproj.github.io/argo-workflows/variables/#global
              - --field
              - |
                *workflow:*
                <https://localhost:2746/workflows/{{ workflow.namespace }}/{{ workflow.name }}?tab=workflow&uid={{ workflow.uid }}|{{ workflow.name }}>
              - --field
              - |
                *owner:*
                {{ workflow.labels.workflows.argoproj.io/owner }}
              - --field
              - |
                *creator:*
                {{ workflow.labels.workflows.argoproj.io/creator }}
              - --field
              - |
                *creationTimestamp:*
                {{ workflow.creationTimestamp }}
              - --field
              - |
                *duration:*
                {{ workflow.duration }}s
