apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-s3-artifact-repository
data:
  default-s3-artifact-repository: |
    s3:
      endpoint: s3.amazonaws.com
      bucket: panicboat-sandbox-723535945756
      region: ap-northeast-1
      insecure: false
      accessKeySecret:
        name: aws-credentials
        key: AWS_ACCESS_KEY_ID
      secretKeySecret:
        name: aws-credentials
        key: AWS_SECRET_ACCESS_KEY
