apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: workflow
  arguments:
    parameters:
      - name: message
        value: this message is default.
  templates:
    - name: workflow
      steps:
        - - name: workflow1
            template: printenv
        - - name: workflow2
            template: whalesay
    - name: printenv
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        name: whalesay
        image: docker/whalesay
        command: [printenv]
        env:
          - name: VAR1
            value: var1
    - name: whalesay
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        name: whalesay
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
        env:
          - name: VAR1
            value: var1
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  suspend: true
  schedule: "* * * * *"
  workflowSpec:
    entrypoint: start-steps
    arguments:
      parameters:
        - name: message
          value: this message from cronworkflow.
    templates:
      - name: start-steps
        steps:
          - - name: workflow-steps
              templateRef:
                name: workflow-template-submittable
                template: printenv
        # 環境変数が追加されなかった
        # podSpecPatch: |-
        #   containers:
        #     - name: main
        #       env:
        #         - name: VAR2
        #           value: var2
    podSpecPatch: |-
      containers:
        - name: main
          env:
            - name: VAR2
              value: var2
    # workflowTemplateRef:
    #   name: workflow-template-submittable
