kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default
resources:
  - configmap/artifact-repositories.yaml
  - role/argo-role.yaml
  - role/argo-server-role.yaml
  - role/executor-role.yaml
  - rolebinding/argo-role-binding.yaml
  - rolebinding/argo-server-role-binding.yaml
  - rolebinding/executor-role-binding.yaml
  - secret/aws-credentials.yaml
  - serviceaccount/executor.yaml
