kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default
resources:
  - clusterrolebinding/argo-binding.yaml
  - clusterrolebinding/argo-server-binding.yaml
  - configmap/artifact-repositories.yaml
  - secret/aws-credentials.yaml
  - secret/slack-config.yaml
  - serviceaccount/argo-server.yaml
  - serviceaccount/argo.yaml
