apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sample-workflow-template
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: this message is default.
  templates:
    - name: main
      steps:
        - - name: step1
            template: whalesay
    - name: whalesay
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        name: whalesay
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: sample-cron-workflow
spec:
  suspend: true
  schedule: "* * * * *"
  timezone: Asia/Tokyo
  workflowSpec:
    entrypoint: main
    arguments:
      parameters:
        - name: message
          value: this message from cronworkflow.
    templates:
      - name: main
        steps:
          - - name: step1
              templateRef:
                name: sample-workflow-template
                template: whalesay
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cronworkflow-status-manager
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: status
        value: suspend
        enum:
          - suspend
          - resume
      - name: cronworkflow
  templates:
    - name: main
      inputs:
        parameters:
          - name: status
            value: "{{workflow.parameters.status}}"
          - name: cronworkflow
            value: "{{workflow.parameters.cronworkflow}}"
      container:
        name: main
        image: public.ecr.aws/bitnami/argo-workflow-cli:latest
        args:
          [
            "cron",
            "{{inputs.parameters.status}}",
            "{{inputs.parameters.cronworkflow}}",
            "-n",
            "default",
          ]
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: suspended-cronworkflow
spec:
  suspend: true
  schedule: "*/5 * * * *"
  timezone: Asia/Tokyo
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: suspended-cronworkflow
              templateRef:
                name: cronworkflow-staus-manager
                template: main
              arguments:
                parameters:
                  - name: status
                    value: suspend
                  - name: cronworkflow
                    value: sample-cron-workflow
