apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-submit-another-workflow
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: submit-workflow
            inline:
              script:
                image: curlimages/curl:latest
                command:
                  - sh
                source: >-
                  curl http://argo-server.argo:2746/api/v1/workflows/default/submit
                  -H "Authorization: $ARGO_TOKEN"
                  -d '{"resourceKind": "WorkflowTemplate", "resourceName": "default-workflow-template", "submitOptions": {"labels": "workflows.argoproj.io/workflow-template=wait"}}'
                envFrom:
                  - configMapRef:
                      name: argo-service-account-token
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: default-workflow-template
spec:
  entrypoint: main
  serviceAccountName: executer
  arguments:
    parameters:
      - name: message
        value: this is message from default service A.
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        name: whalesay
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
