apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-default-executor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-default-executor-role
subjects:
  - kind: ServiceAccount
    name: argo-workflows-default-executor
